services:
  postgres:
    image: postgres:16
    container_name: pg_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vnstocks
    ports:
      - "5432:5432"
    volumes:
      - pg_data_vnstocks:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vnstocks"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data_vnstocks: